# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Rory
tagline:             'stuff about computer science'
description:         'A blog that records things I learn from computer Scinece'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
excerpt_separator:  '<!-- more -->'

# Where are tags and categories displayed
tag_page: '/Tags/'
# category_page: '/blog/categories/'

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
